### ISSUE TITLE
Feature request - Cache logged in user

### ISSUE THREAD

**Issue by kristijandraca** [juanitogan/godot-firebase-lite#1]
It would be a nice addition to this library if we could save the user so next time he opens the app, the sign-in process is automatic. Maybe some kind of config file
https://docs.godotengine.org/en/stable/classes/class_configfile.html#class-configfile

**Comment by juanitogan** [comment]
Beyond the scope of this project.  This is an implementation of the Firebase API and nothing more; and a lite one at that.

**Comment by kristijandraca** [comment]
I get that, but it would be great if this lib could mimic behavior from Firebase Android/iOS SDK
Once the user is logged in, auth state is saved for the next time a user opens the app.

**Comment by juanitogan** [comment]
Okay, I see what you're thinking now.  I don't know anything about those SDKs and that feature, but it's not hard to guess that they are likely tapping into some platform-specific features for credential management to do that securely.  I have no plans for platform-dependent features here.  That would be up to you, Godot, your target platforms, and who knows how many other libraries to figure out how to do that according to your security specs.

**Comment by juanitogan** [comment]
After thinking about this a bit more, yes, if someone wanted to create some optional packages for platform-specific features such as mentioned in the third comment, it would be a fine addition to the project.  Otherwise, however, I'm closing this because such a general-purpose feature does not exist in FB (as I understand the request) and is out of scope.  If wanting a specific feature from a specific SDK, please open an issue for each, with links to the feature in the SDK, and I'll leave it open if it fits the scope.  I, personally, am too busy with other projects, but someone else may pick it up.
