### ISSUE TITLE
[feature request] - When game is connected successfully to Firebase, or when game cannot connect

### ISSUE THREAD

**Issue by JapanYoshi** [juanitogan/godot-firebase-lite#3]
If requesting a feature, please add links to the Firebase API or SDK document pages that describe the feature you want.  If one of the SDKs does not have the feature you are looking for, odds are it will not be invented for this "Godot SDK."

https://firebase.google.com/docs/reference

If you don't know which SDK to start digging through for your feature, it may help to know that this project runs on the Firebase REST API and is based heavily on the JavaScript SDK, with bits from the Java and Unity SDKs.

----

I want to know how I can tell when my Godot game could successfully connect to the Firebase database, and when my Godot game could NOT connect there, so that I can implement some kind of loading screen, error display, or dedicated "offline mode".

**Comment by juanitogan** [comment]
Firebase is a near-realtime database and, thus, the responses are always nearly instant.  Also, if you have a user, for example, that is having trouble connecting to the database, odds are at least a thousand to one that it is something other than Firebase.  Thus, such features for handling all scenarios that can cause connection issues are up to you to build.  This API already returns FirebaseError from all calls to Firebase to help you build such features.  I don't yet understand what else you might need.

If, maybe, you are hoping for a function that checks Google's dashboard for uptime status, I suppose you could do that.  That would, however, still be something outside of this API... and useful maybe 0.0001% of the time.

If, however, this API is missing some messaging that would be helpful to you in building more durable communications with Firebase, please link a page from one of the other APIs that shows me the messages you are looking for.  FirebaseError likely already returns them, but maybe I missed something.

Personally, if wanting an offline mode (which is always a good idea), I would give the user a way to enable that manually rather than trying to automate it (or maybe do both). 

Also, if you're using another API on top of Firebase (such as WebRTC like I am) any perceived slowness will be due to that other API and not Firebase (such as how slow WebRTC handshaking can be).  These are things Firebase cannot know about (it's just a simple database) and, thus, you need to build things like loading messaging for these other tools yourself (which I do around WebRTC).

**Comment by JapanYoshi** [comment]
I don't know what you're talking about. I want the game to do something different when it can't connect to Firebase when it tries to for the first time. I want to show the user that the game is trying to connect to Firebase, then that it succeeded in that.

**Comment by juanitogan** [comment]
There is no such thing on the web.  Basically, every service request on the web is its own brief "connection" and the response either makes it back to you or it doesn't.  With Firebase, the response is guaranteed to be near instant, so there is no waiting.  You should know within half a second if your last request was valid, errored, or got lost.  What your game chooses to do after an error is up to you.  You can declare Firebase dead at that point, or you can try again -- up to you.

The idea of what "connected" means to your game is something you have to invent.  This is true with every app on the net.  Whether that means authenticating and exchanging security tokens with each request ("logged in"), or something else (like a WebRTC "connection" between players), that is entirely up to you.

You can set your Firebase database to require authentication via its own authentication system, but that's another topic entirely, and what FirebaseAuthLite is for.

**Comment by JapanYoshi** [comment]
I want to stop the game from connecting or listening to Firebase when it doesn't need to (e.g. in the menus before/after a match is in progress). I just want to make sure that Firebase is available once the player wants to start the game, and do different things depending on whether Firebase is available. How hard is this? Is the only way to do this to send a dummy request to see if it errors out? For what causes CAN it error out?

**Comment by juanitogan** [comment]
It sounds like you are missing some very fundamental things about how internet services work.  I can help a tiny bit with the basics but can't help a lot.  It might help you to take some of your questions to places with more traffic for more help than I can give.  Basically, if you're not making a request to Firebase, you're not connected.  It really is as simple as that.  To rephrase what I said before: All HTTP requests are instant and individual connections.  Even the authenticated requests are instant and individual.  You are only "connected" to a web service like Firebase for as long as it takes to get a response.  Then, it totally forgets about you, forever.  That's why you can't expect requests to come back in the same order they were sent.  Firebase sees no relationship between them.  Everything it needs to know about who you are is sent with each request.  All web services are like this.

The only time this changes on the net is when you use some sort of other tech besides (or on top of) HTTP such as SSE or P2P or who knows what.  Thus, with Firebase, and with this API, you can set up SSE listeners as well as making HTTP requests.  But, even then, you aren't really "connected" like you may be thinking.  If you want to stop listening to data changes over SSE, then just disable any listeners you have set up.  But, this is more about signal programming in Godot than it is about this API.  Thus, you need to first learn how to use signals in Godot before the listener signals in this API will make sense to you.  Again, the best place for that kind of help is a place with more traffic than here, like the Godot boards.

As to what CAN cause an error, like I said before: just about anything -- with extremely small odds that it will be anything related to a Firebase outage or bug.  For me, I spend no time or effort programming for a Firebase outage because it simply isn't worth the time to do so.   The odds of it are too small compared to the many many things that can go wrong with a user's internet service (that is, the HTTP connection itself).  And, programming for all that is, simply, hard work.  For me, it is best to focus on the game and worry about connection issues only as they come up.  You are welcome to do otherwise, you'll just have to dig through a few hundred HTTP and Firebase error codes on your own -- all of which, yes, this API already returns to you for you to do with as you will.  Trying something and responding to errors is the bread and butter of programming.
