### ISSUE TITLE
Question: What does `func _init(ref: Object).(ref):` mean?

### ISSUE THREAD

**Issue by JapanYoshi** [juanitogan/godot-firebase-lite#4]
This is not a bug, but I've been trying to translate this library from GDScript 3 to GDScript 4, and came across this line in firebase_auth_lite/event_processor.gd:

https://github.com/juanitogan/godot-firebase-lite/blob/b29a90ff302940e448f4fac5f202689ad8e2b28f/firebase_database_lite/event_processor.gd#L9

I've never seen this syntax before, so I don't know what it's doing or what it would be in GDScript 4.

Though, since there's nothing in the function except `pass`, I wonder if I can just comment it out of the script.

**Comment by juanitogan** [comment]
Yeah, I remember having to dig that up for some specific reason... but I don't currently remember why.  It's been a long time since I've done any GDScripting.  Give me a few minutes and I'll try to dig it up again.

I was watching the evolution of Godot 4 while writing this and remember hoping that GDScript 2.0 (or whatever they called it) would allow me to do a few things different.  Namely, poor class handling in GDScript is what I struggled with most and there was hope I could design the classes a bit different in the new version.  Particularly, circular references are not allowed and so I had to build an extra class here and there to get around it... I think... (and then still had to do dummy edits in some classes every time the interpreter got confused about it all).

**Comment by juanitogan** [comment]
I haven't found it yet... but I'm starting to get some fuzzy memory that it might pass this class' ref to the parent class' _init().

**Comment by juanitogan** [comment]
Yep, that was the clue I needed to search for it:

https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_basics.html#class-constructor

Even though the arguments are the same in this case, it appears a constructor (versus a regular function) won't pass the args unless you do it explicitly like this.

**Comment by JapanYoshi** [comment]
https://github.com/JapanYoshi/godot-4-firebase-lite/commit/a24ce276bd9597d98c15e23df38a0bce051811c4

Replaced this part with proper Godot 4 syntax!
